stages:
    - test
    - build 
yarn_test:
    image: node:18-bullseye 
    stage: test
    script:
        - yarn install 
        - yarn test 

build_image:
    stage: build 
    image: docker:24
    services:
        - docker:24-dind
    variables:
        Docker_User : mohamedaydi
    before_script:
        - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin 
    script:
        - docker build -t mohamedaydi/demo-app:juice-shop-1.1 .
        - docker push mohamedaydi/demo-app:juice-shop-1.1
